package com.android.multistream.network.mixer.models.channel

data class GameChannels(
	val featured: Boolean? = null,
	val viewersTotal: Int? = null,
	val viewersCurrent: Int? = null,
	val badgeId: String? = null,
	val hasTranscodes: Boolean? = null,
	val interactive: Boolean? = null,
	val bannerUrl: String? = null,
	val description: String? = null,
	val createdAt: String? = null,
	val coverId: String? = null,
	val hasVod: Boolean? = null,
	val transcodingProfileId: Any? = null,
	val numFollowers: Int? = null,
	val thumbnailId: String? = null,
	val id: Int? = null,
	val hosteeId: String? = null,
	val partnered: Boolean? = null,
	val ftl: Int? = null,
	val updatedAt: String? = null,
	val audience: String? = null,
	val thumbnail: ThumbNail? = null,
	val interactiveGameId: String? = null,
	val languageId: String? = null,
	val userId: Int? = null,
	val featureLevel: Int? = null,
	val suspended: Boolean? = null,
	val token: String? = null,
	val deletedAt: String? = null,
	val vodsEnabled: Boolean? = null,
	val costreamId: String? = null,
	val name: String? = null,
	val online: Boolean? = null,
	val typeId: Int? = null,
	val user: User? = null
)
